a=10 
b=2 
print('a+b=',a+b) #12
print('a-b=',a-b) #8
print('a*b=',a*b) #20
print('a/b=',a/b) #5.0 '/' operators always gives float as output
print('a//b=',a//b) #5
print('a%b=',a%b) #0
print('a**b=',a**b) #100
